export const ADDON_ENUM_LIBRARY                       = 'ADDON_ENUM_LIBRARY';
export const ADDON_ENUM_LIBRARY_PENDING               = 'ADDON_ENUM_LIBRARY_PENDING';
export const ADDON_ENUM_LIBRARY_REJECTED              = 'ADDON_ENUM_LIBRARY_REJECTED';
export const ADDON_ENUM_LIBRARY_FULFILLED             = 'ADDON_ENUM_LIBRARY_FULFILLED';
