export const ADDON_ENUM_UTILITY                       = 'ADDON_ENUM_UTILITY';
export const ADDON_ENUM_UTILITY_PENDING               = 'ADDON_ENUM_UTILITY_PENDING';
export const ADDON_ENUM_UTILITY_REJECTED              = 'ADDON_ENUM_UTILITY_REJECTED';
export const ADDON_ENUM_UTILITY_FULFILLED             = 'ADDON_ENUM_UTILITY_FULFILLED';
