export const ADDON_ENUM_CATEGORY                      = 'ADDON_ENUM_CATEGORY';
export const ADDON_ENUM_CATEGORY_PENDING              = 'ADDON_ENUM_CATEGORY_PENDING';
export const ADDON_ENUM_CATEGORY_REJECTED             = 'ADDON_ENUM_CATEGORY_REJECTED';
export const ADDON_ENUM_CATEGORY_FULFILLED            = 'ADDON_ENUM_CATEGORY_FULFILLED';
