export const PENDING_ADDON_SUBMIT                     = 'PENDING_ADDON_SUBMIT';
export const PENDING_ADDON_SUBMIT_PENDING             = 'PENDING_ADDON_SUBMIT_PENDING';
export const PENDING_ADDON_SUBMIT_REJECTED            = 'PENDING_ADDON_SUBMIT_REJECTED';
export const PENDING_ADDON_SUBMIT_FULFILLED           = 'PENDING_ADDON_SUBMIT_FULFILLED';

export const PENDING_ADDON_LIST                       = 'PENDING_ADDON_LIST';
export const PENDING_ADDON_LIST_PENDING               = 'PENDING_ADDON_LIST_PENDING';
export const PENDING_ADDON_LIST_REJECTED              = 'PENDING_ADDON_LIST_REJECTED';
export const PENDING_ADDON_LIST_FULFILLED             = 'PENDING_ADDON_LIST_FULFILLED';

export const PENDING_ADDON_DELETE                     = 'PENDING_ADDON_DELETE';
export const PENDING_ADDON_DELETE_PENDING             = 'PENDING_ADDON_DELETE_PENDING';
export const PENDING_ADDON_DELETE_REJECTED            = 'PENDING_ADDON_DELETE_REJECTED';
export const PENDING_ADDON_DELETE_FULFILLED           = 'PENDING_ADDON_DELETE_FULFILLED';

export const PENDING_ADDON_EDIT                       = 'PENDING_ADDON_EDIT';
export const PENDING_ADDON_EDIT_PENDING               = 'PENDING_ADDON_EDIT_PENDING';
export const PENDING_ADDON_EDIT_REJECTED              = 'PENDING_ADDON_EDIT_REJECTED';
export const PENDING_ADDON_EDIT_FULFILLED             = 'PENDING_ADDON_EDIT_FULFILLED';

export const PENDING_ADDON_ACCEPT                     = 'PENDING_ADDON_ACCEPT';
export const PENDING_ADDON_ACCEPT_PENDING             = 'PENDING_ADDON_ACCEPT_PENDING';
export const PENDING_ADDON_ACCEPT_REJECTED            = 'PENDING_ADDON_ACCEPT_REJECTED';
export const PENDING_ADDON_ACCEPT_FULFILLED           = 'PENDING_ADDON_ACCEPT_FULFILLED';
