export const PENDING_USER_NEW                         = 'PENDING_USER_NEW';
export const PENDING_USER_NEW_PENDING                 = 'PENDING_USER_NEW_PENDING';
export const PENDING_USER_NEW_REJECTED                = 'PENDING_USER_NEW_REJECTED';
export const PENDING_USER_NEW_FULFILLED               = 'PENDING_USER_NEW_FULFILLED';

export const PENDING_USER_TYPE_ENUM                   = 'PENDING_USER_TYPE_ENUM';
export const PENDING_USER_TYPE_ENUM_PENDING           = 'PENDING_USER_TYPE_ENUM_PENDING';
export const PENDING_USER_TYPE_ENUM_REJECTED          = 'PENDING_USER_TYPE_ENUM_REJECTED';
export const PENDING_USER_TYPE_ENUM_FULFILLED         = 'PENDING_USER_TYPE_ENUM_FULFILLED';

export const PENDING_USER_REMOVE_TOKEN                = 'PENDING_USER_REMOVE_TOKEN';
