export const RECAPTCHA_PUBLIC_KEY                     = 'RECAPTCHA_PUBLIC_KEY';
export const RECAPTCHA_PUBLIC_KEY_PENDING             = 'RECAPTCHA_PUBLIC_KEY_PENDING';
export const RECAPTCHA_PUBLIC_KEY_REJECTED            = 'RECAPTCHA_PUBLIC_KEY_REJECTED';
export const RECAPTCHA_PUBLIC_KEY_FULFILLED           = 'RECAPTCHA_PUBLIC_KEY_FULFILLED';

export const RECAPTCHA_RESPONSE                       = 'RECAPTCHA_RESPONSE';
export const RECAPTCHA_RESPONSE_RESET                 = 'RECAPTCHA_RESPONSE_RESET';
export const RECAPTCHA_RESET                          = 'RECAPTCHA_RESET';
export const RECAPTCHA_RESET_DONE                     = 'RECAPTCHA_RESET_DONE';
